name: frontend
description: "A Flutter application for Sri Lankan Car Valuation Engine."
publish_to: 'none'

version: 1.0.0+1

# Add or update this environment block:
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true